### ISSUE TITLE
Rename workers to...

### ISSUE THREAD

**Issue by darrnshn** [NICTA/stateline#104]
Found some terminology from other distributed architectures/OS X background process names:
- Supervisor/Manager (but doesn't really supervise/manage)
- Client (from a proletariat view, the workers request jobs, but personally I think if we ever factor out the delegator into its own distributed job queue system, then the clients would be the requester, not the worker).
- Interface/Host/Node (a bit ambiguous/generic)
- Connector/Adaptor/**Session**/Helper/**Agent**/Proxy (less generic)
- **Tracker** (kinda keeps track of jobs for a worker...used for a similar purpose in MapReduce)
- Broker (but it doesn't really broker)
- Consumer (but it's not pub/sub and there's no producer)
- Fancy name (some frameworks use fancy names like Nimbus or Squid, but seems gratuitous).

Ideally, it'd be something like interface but less ambiguous:

**Comment by lmccalman** [comment]
I like Agent!!!

**Comment by darrnshn** [comment]
Agent it is.
