### ISSUE TITLE
Have sensible defaults for job types

### ISSUE THREAD

**Issue by darrnshn** [NICTA/stateline#41]
For very simple simulations, we don't generally need to complicate things with job types. It would be good to implement default behaviour for when job types aren't specified:

* Server uses **default**, worker uses **default**: Only one job type is used. Worker receives all jobs.
* Server uses **default**, worker specifies **job type(s)**: Worker receives no jobs. *Should not be used, and a warning should be given if detected*.
* Server specifies **job type(s)**, worker uses **default**: Worker receives all jobs.
* Server specifies **job type(s)**, worker specifies **job type(s)**: Worker only receives job types it specifies.

So in general, specifying no job type on the worker side is equivalent to subscribing to all job types. If server uses default, then all workers must use default. As for what string to represent the default job type, perhaps the empty string since it saves space?

**Comment by lmccalman** [comment]
no longer relevant as we now use job indices not types
