### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by youph** [NICTA/stateline#45]
Having followed the 'easy install' steps all the way to 'make' in the build/release directory, I get the following error when running make (running make in both /build/release and /build/debug tried):

```
[ 19%] Building CXX object src/comms/CMakeFiles/router.dir/router.cpp.o
/home/yuriy/Projects/stateline/src/comms/router.cpp: In constructor ‘stateline::comms::SocketRouter::SocketRouter(const string&, const std::vector<stateline::comms::Socket*>&)’:
/home/yuriy/Projects/stateline/src/comms/router.cpp:35:59: error: no matching function for call to ‘std::vector<zmq_pollitem_t>::push_back(<brace-enclosed initializer list>)’
         pollList_.push_back({s->socket_, 0, ZMQ_POLLIN, 0});
                                                           ^
/home/yuriy/Projects/stateline/src/comms/router.cpp:35:59: note: candidates are:
In file included from /usr/include/c++/4.8/vector:64:0,
                 from /home/yuriy/Projects/stateline/src/comms/messages.hpp:14,
                 from /home/yuriy/Projects/stateline/src/comms/router.hpp:19,
                 from /home/yuriy/Projects/stateline/src/comms/router.cpp:11:
/usr/include/c++/4.8/bits/stl_vector.h:901:7: note: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = zmq_pollitem_t; _Alloc = std::allocator<zmq_pollitem_t>; std::vector<_Tp, _Alloc>::value_type = zmq_pollitem_t]
       push_back(const value_type& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:901:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const value_type& {aka const zmq_pollitem_t&}’
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = zmq_pollitem_t; _Alloc = std::allocator<zmq_pollitem_t>; std::vector<_Tp, _Alloc>::value_type = zmq_pollitem_t]
       push_back(value_type&& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘std::vector<zmq_pollitem_t>::value_type&& {aka zmq_pollitem_t&&}’
make[2]: *** [src/comms/CMakeFiles/router.dir/router.cpp.o] Error 1
make[1]: *** [src/comms/CMakeFiles/router.dir/all] Error 2
make: *** [all] Error 2

```

Any ideas on how to get through?

Cheers!

**Comment by lmccalman** [comment]
Hey Yuri, 
How old is your C++ compiler/library? And did zmq build correctly? These are probably the two avenues i'd look at first. Master builds fine on our machines and all the tests pass so it must be something to do with your environment....

**Comment by youph** [comment]
Hey Lachlan,

  1.  My c++ compiler is: g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2. I also have clang, not sure which one is used when building stateline – I presume it’s g++.
  2.  Zeromq was built without any errors.

I’ll try to go over all the prereqs one by one to see whether there are any errors building any of them (previously I just ran fetch_all.sd) Meanwhile, if you have any other ideas, please let me know.

Cheers,
Yuriy

**Comment by youph** [comment]
Here’s what I get when building the prereqs one by one:

Boost: a bunch of warnings about some types locally defined but not used; and a bunch of notes, but I don’t see any errors

Eigen 3.2.0: some Failures during config process, but make install went without errors

google-log (glog) 0.3.3: make install produced some warnings about deprecated features, etc., but didn’t produce errors.

google-test (gtest) 1.7.0: files unzipped ok

zeromq 4.0.3: no errors

cppzeromq: no errors

json: no errors

Hmmm…

**Comment by youph** [comment]
Lachlan,
When I install boost, I get the following “no” checks – is this ok?

Performing configuration checks

    - arm                      : no  (cached)
    - mips1                    : no  (cached)
    - power                    : no  (cached)
    - sparc                    : no  (cached)
    - x86                      : yes (cached)
    - has_icu builds           : no  (cached)
warning: Graph library does not contain MPI-based parallel components.
note: to enable them, add "using mpi ;" to your user-config.jam
    - zlib                     : no  (cached)
    - iconv (libc)             : yes (cached)
    - icu                      : no  (cached)
    - icu (lib64)              : no  (cached)
    - compiler-supports-ssse3  : yes (cached)
    - lockfree boost::atomic_flag : yes (cached)
    - compiler-supports-avx2   : yes (cached)
    - gcc visibility           : yes (cached)
    - long double support      : yes (cached)
warning: skipping optional Message Passing Interface (MPI) library.
note: to enable MPI support, add "using mpi ;" to user-config.jam.
note: to suppress this message, pass "--without-mpi" to bjam.
note: otherwise, you can safely ignore this message.
    - zlib                     : no  (cached)

Also, which python (2.7 or 3) is required by stateline?

Cheers,
Yuriy

**Comment by youph** [comment]
…Also, you might want to add in the prerequisites the following:

  *   bz2 library
  *   Python developers tools (?), I.e., python-dev libxml2-dev libxslt-dev

**Comment by lmccalman** [comment]
Thanks Yuri,
If you're still having trouble, why don't you come down to level 3 and we can have a look.

**Comment by youph** [comment]
I’m trying to install it in a fresh VM box with Fedora on it (was doing it on Ubuntu before – not sure whether this matters), we’ll see how it goes.

Cheers,
Yuriy

**Comment by youph** [comment]
Lachlan,
FYI: I've tried to build stateline in the latest ubuntu 15.04 environment, and got the same error at the end.
In addition, here are the things I had to install additionally, in response to various errors thrown by the fetch-all.sh script:
 - bzip2
 - libbz2-dev
 - python-dev
 - doxygen

Yuriy

**Comment by youph** [comment]
Thanks Lachlan, the compilation works now. I have further issues with demos, but those are separate issues :)

**Comment by dtpc** [comment]
@youph / @lmccalman, what was the specific solution to the original error? I'm getting the same when building stateline on a Travis CI build server.

```
[ 19%] Building CXX object src/comms/CMakeFiles/router.dir/router.cpp.o
/home/travis/build/dtpc/stateline/src/comms/router.cpp: In constructor ‘stateline::comms::SocketRouter::SocketRouter(const string&, const std::vector<stateline::comms::Socket*>&)’:
/home/travis/build/dtpc/stateline/src/comms/router.cpp:35:59: error: no matching function for call to ‘std::vector<zmq_pollitem_t>::push_back(<brace-enclosed initializer list>)’
         pollList_.push_back({s->socket_, 0, ZMQ_POLLIN, 0});
                                                           ^
/home/travis/build/dtpc/stateline/src/comms/router.cpp:35:59: note: candidates are:
In file included from /usr/include/c++/4.8/vector:64:0,
                 from /home/travis/build/dtpc/stateline/src/comms/messages.hpp:14,
                 from /home/travis/build/dtpc/stateline/src/comms/router.hpp:19,
                 from /home/travis/build/dtpc/stateline/src/comms/router.cpp:11:
/usr/include/c++/4.8/bits/stl_vector.h:901:7: note: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = zmq_pollitem_t; _Alloc = std::allocator<zmq_pollitem_t>; std::vector<_Tp, _Alloc>::value_type = zmq_pollitem_t]
       push_back(const value_type& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:901:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const value_type& {aka const zmq_pollitem_t&}’
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = zmq_pollitem_t; _Alloc = std::allocator<zmq_pollitem_t>; std::vector<_Tp, _Alloc>::value_type = zmq_pollitem_t]
       push_back(value_type&& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘std::vector<zmq_pollitem_t>::value_type&& {aka zmq_pollitem_t&&}’
make[2]: *** [src/comms/CMakeFiles/router.dir/router.cpp.o] Error 1
make[1]: *** [src/comms/CMakeFiles/router.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by lmccalman** [comment]
Ah sorry Dave, I though Yuri was going to commit this change. In the router.cpp, the socket has to be explicitly cast to a void pointer for the initializer list style:
replace this:
 pollList_.push_back({s->socket_, 0, ZMQ_POLLIN, 0})
with this:
 pollList_.push_back({(void*)s->socket_, 0, ZMQ_POLLIN, 0})

Note that I'm intentionally casting the socket itself, not a pointer to it!
That should fix the problem. Some compilers seem to do fine, some not!

**Comment by dtpc** [comment]
Thanks. I was getting the error on Ubuntu with 4.8.1.
