### ISSUE TITLE
Running in docker containers

### ISSUE THREAD

**Issue by dfalster** [NICTA/stateline#50]
I managed to build and load the docker container (using `Dockerfile`) and then run stateline server inside the container. But then how do I get a second process (worker) running and communicating with the server. Either I need a second container, or a second terminal within the first container.

**Comment by richfitz** [comment]
I spent some time on this yesterday and have written up notes [here](https://gist.github.com/richfitz/ca1efe5041493edf39e7)

Basically:

* Running stateline in a container and getting the worker process working in that container with `docker exec` will work fine for me, at least for now (especially if the plan is to run this in Linux environments).
* If it's possible to interact with the containers exposing ports that might be nicer, but I think I'd need additional information to make that go.
* There's a small missing bit (annealLength) in the python config
* The worker shut down on the Python case does not look clean to me
* Not in the gist, but I'd like to know what stateline-client is doing and why that needs to be separate from the python worker, plus if it's possible to combine the two.
* The R zmq bindings look pretty ill-suited to what we need here and I think I will have to quickly roll my own (they only communicate serialised R objects which is totally inappropriate for what we want).

**Comment by richfitz** [comment]
Also done in https://github.com/traitecoevo/stateliner

I still think that linked containers would be heaps nicer here.  Any chance that could be enabled in the official stateline docker container?

**Comment by lmccalman** [comment]
Definitely -- will sort it out on Monday =)

**Comment by lmccalman** [comment]
Okay I've commited some new docker files and a short README. Have a look and if it's okay for now I'll close this issue.
