### ISSUE TITLE
Detailed specs for running R client

### ISSUE THREAD

**Issue by dfalster** [NICTA/stateline#51]
Discussed with @lmccalman what was needed to get stateline running with R client. 

Basically we need an equivalent of `src/bin/demo-worker.py`. The client communicates stateline-server via `./stateline-client`, which is set up to receive commands via zero-mq. So most of `src/bin/demo-worker.py` is about handling this comms. The actuall likelihood calculations are done in `nll` function (negative log likelihood - in demo just a Gaussian). 

@richfitz and I are keen to get running. But while we could probably reverse engineer everything that the `src/bin/demo-worker.py` script is doing, we'd find it very useful if someone could write out specs a little more. Is that possible?

**Comment by lmccalman** [comment]
Yeah we can definitely do this -- though probably not till Monday.

**Comment by richfitz** [comment]
In the end I got most of this working (but see #50), and I think that I may not need much help here, so hold off for now.

**Comment by richfitz** [comment]
This is done and can be closed now.  See https://github.com/traitecoevo/stateliner for my investigations.  If someone from the NICTA team could check that the approach there works, I'd be grateful.

**Comment by dfalster** [comment]
Confirming that @richfitz's stateliner code also works for me.
