### ISSUE TITLE
Adaption mechanism rework

### ISSUE THREAD

**Issue by AlistaiReid** [NICTA/stateline#84]
Al is prototyping a new parameter-free adaption. The adaption learns a linear regressor mapping sigma to accept rate that incrementally trains on the noisy accepts and rejects wrt squared error. The model has an analytic inverse so it can then be used to predict which sigma will achieve a target accept rate.

**Comment by darrnshn** [comment]
This sounds exciting!!

**Comment by AlistaiReid** [comment]
Yeah, I've got a prototype working and it looks promising!

Hows the internship?

**Comment by darrnshn** [comment]
Yeah it's going well! This is pretty cool...and it has the added bonus of clearing up the configuration file. Could this be extended to take into account the location of the chains as well, so you get different sigmas for different regions?
